options = 
{
	{ 
		default = 1.5, 
		label = "Difficulty", 
		help = "Enemy unit count multiplier", 
		key = 'opt_difficulty', 
		pref = 'opt_difficulty', 
		values = { 
			{text = "Bce norm (default)", help = "", key = 1.0, }, 
			{text = "Alan Dark", help = "", key = 2.0, }, 
			{text = "Mikvini", help = "", key = 3.0, }, 
			{text = "RespectiC", help = "", key = 4.0, }, 
			{text = "Korogec", help = "", key = 5.0, }, 
			{text = "Yasav", help = "", key = 6.0, }, 
			{text = "Empty", help = "", key = 7.0, }, 
			{text = "Bfox", help = "", key = 8.0, }, 
			{text = "MasterFaker", help = "", key = 9.0, }, 
			{text = "DarkSide", help = "", key = 10.0, }, 
			{text = "Imperator_ArthasDK", help = "", key = 15.0, }, 
			{text = "Tyrtuiklo", help = "", key = 20, }, 
		}, 
	}, 
	{ 
		default = 1, 
		label = "Startup Time", 
		help = "How many seconds until first wave spawns", 
		key = 'opt_startupTime', 
		pref = 'opt_startupTime', 
		values = { 
			{text = "300 secs", help = "", key = 300, }, 
			{text = "600 secs", help = "", key = 600, }, 
			{text = "900 secs",help = "", key = 900, }, 
			{text = "1200 secs",help = "", key = 1200, }, 
			{text = "1800 secs",help = "", key = 1800, }, 
			{text = "3600 secs",help = "", key = 3600, }, 
			{text = "60 secs",help = "", key = 60, }, 
		}, 
	}, 
	{ 
		default = 10, 
		label = "Wave Delay Time", 
		help = "How many seconds between each wave", 
		key = 'opt_waveTime', 
		pref = 'opt_waveTime', 
		values = { 
			{text = "10 secs (default)", help = "", key = 10, }, 
			{text = "60 secs",help = "", key = 60, }, 
			{text = "120 secs",help = "", key = 120, }, 
			{text = "180 secs",help = "", key = 180, }, 
			{text = "300 secs",help = "", key = 300, }, 
			{text = "600 secs",help = "", key = 600, }, 
			{text = "1200 secs",help = "", key = 1200, }, 
		}, 
	}, 
	{ 
		default = 1, 
		label = "Defense Object", 
		help = "The object you have to defend", 
		key = 'opt_defenseObject', 
		pref = 'opt_defenseObject', 
		values = { 
			{text = "Nihuya",help = "", key = -1, }, 
			{text = "BSCC (default)", help = "", key = 1, }, 
			{text = "Paragon",help = "", key = 2, }, 
			{text = "Mavor",help = "", key = 3, }, 
			{text = "Kakoy-to domik",help = "", key = 4, }, 
		}, 
	}, 	
};